# 예외 처리하기

- 예외란 미처 처리하지 못한 에러를 말한다. 

- 멀티쓰레드 같은 경우 쓰레드가 하나 죽어도 다른 쓰레드가 대신 할수 있지만 노드는 쓰레드가 하나라서 하나가 죽으면 전체 서버가 죽는데 

- 그래서 필수로 예외를 처리해야한다.

```js
setInterval(() => {
    console.log('시작');
    try {
        throw new Error('서버를 고장내주마');
    } catch(error){
        console.error(error);
    }
}, 1000)
```

- 노드에서 에러를 발생시키는 법은 throw 하는 것이다.

- 이러한 `throw`를 받아주는 `try catch`가 있다. 에러가 날것 같은것은 시도한 다음 에러가 나면 캐치해서 처리를 한다. 그러면 프로그램은 죽지 않는다.

- `try catch`를 쓰지 않는게 좋다. 에러가 날 상황이면 에러를 내지말고 에러에 대한 처리를 해야한다. 

- 하지만 async / await 처럼 어쩔 수 없이 try/catch 를 써야 하는 경우도 있어요.

```js
setInterval(() => {
    fs.unlink('./asadfa.js', err => {
        if(err){
            console.log('시작')
            console.log(err)
            console.log('끝')
        }
    })
}, 1000)
```

- 비동기 메서드들은 콜백에서 에러가 들어온다. 에러가 나지면 똑같이 실행이 된다. 

- 노드 내장된 메서드가 발생한 에러는 에러가 나도 프로세스를 멈추진 않는다. 따로 처리할 필요가 없다. 기록해서 해결한 방안만 찾으면 된다.

- `try catch`를 안써도 에러를 잡는 방법이 있다. 

```js
process.on('uncaughtException', err => {
    console.error('예기치 못한 에러',err);
})
setInterval(() => {
    throw new Error('서버를 고장내주마')
}, 1000)
setInterval(() => {
    console.log('실행됩니다.')
} , 2000)
```

- `process`에 `uncaughtException`을 하면 캐치로 안잡아도 한번에 처리하는 할 수 있다.

- 모든 에러를 해결할수 있지만 문제는 에러가 계속 난다는 것이다

- uncaughtException에 의존하지 말고 근본적인 에러의 원인을 해결합시다.

- `process uncaughtException`리스너에 서버를 복구하는 코드를 넣을수 있다 하지만 권장되지 않는다. 콜백이 실행되는 것을 보장하지 않는다. 